name: Publish Release

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore: 
      - .github/workflows/*

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'Flow.Launcher.Plugin.CPPreference/plugin.json'
          prop_path: 'Version'
      - run: echo ${{steps.version.outputs.prop}} 
      - name: Build
        run: |
          dotnet publish 'Flow.Launcher.Plugin.CPPreference/Flow.Launcher.Plugin.CPPreference.csproj' --framework netcoreapp3.1  -c Release -o "CPPreference"
          7z a -tzip "Flow.Launcher.Plugin.CPPreference.zip" "CPPreference/*"
          rm -r "CPPreference"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "Flow.Launcher.Plugin.CPPreference.zip"
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
