name: Publish Release

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore: 
      - .github/workflows/*

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'Flow.Launcher.Plugin.CPPreference-flow-plugin/plugin.json'
          prop_path: 'Version'
      - run: echo ${{steps.version.outputs.prop}} 
      - name: Build
        run: |
          dotnet publish 'Flow.Launcher.Plugin.CPPreference-flow-plugin/Flow.Launcher.Plugin.CPPreference-flow-plugin.csproj' --framework netcoreapp3.1  -c Release -o "CPPreference-flow-plugin"
          7z a -tzip "Flow.Launcher.Plugin.CPPreference-flow-plugin.zip" "CPPreference-flow-plugin/*"
          rm -r "CPPreference-flow-plugin"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "Flow.Launcher.Plugin.CPPreference-flow-plugin.zip"
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
